### ISSUE TITLE
Zelda TODO

### ISSUE THREAD

**Issue by glaebhoerl** [glaebhoerl/personal#38]
- [ ] Is the dude selling an Ancient Core near Hateno Village still there?
- [ ] Shrine on the island
- [ ] Catch up with Hestu
- [ ] Fire Rod
- [ ] Kill the monsters on Hateno Beach
- [ ] Find out who or what is standing on the small island
- [ ] Find the last missing monument shard
- [ ] Travel to the strange island with the voice (depends: more stamina)
- [ ] Cook all the things
- [ ] Find the Shiekah Tower of the fisherman people
- [ ] Visit the malice-blighted old castle thingie
  - [ ] White horse?
  - [ ] Horse statue?
- [ ] Find researcher Robbie at Akkala
- [ ] Catch up with carpenter dude (Hobson?)
- [ ] Try to bomb a Guardian near the two mountains stable?

# Questions
- [ ] What are you supposed to do with rings of plants in the water?
- [ ] Do I get anything for freeing Nayra?

# Later
- [ ] Upgrade Stasis
- [ ] Red lynel at the Purifier Lake
- [ ] Treasure chest in the conveyor belt shrine
- [ ] A Major Test of Strength
- [ ] Shiekah ball-receptacle thing in the forest outside Kokoriko Village
